### ISSUE TITLE
Decidir un nombre para el proyecto

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/project-x#1]
Hay que decidir un nombre con gancho para el proyecto.

**Comment by CeciliaVa** [comment]
¿Esto cómo se vota?

**Comment by VentressAsajj** [comment]
@David-Estevez esta issue se puede cerrar. El proyecto se llama Project X? @jorgercobo ?

**Comment by David-Estevez** [comment]
Llevo tanto tiempo llamándolo por ese nombre que a mi ya me pega bastante, sí que por mi ok.

@jorgercobo ?

**Comment by jorgercobo** [comment]
Me habría gustado un nombre más descriptivo, pero adelante, ya es Project X en mi coraçón
