### ISSUE TITLE
Soporte para cámara FPV

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/project-x#8]
El coche necesita un soporte para la cámara. Si es impreso en 3D, hay que tener en cuenta que el cuerpo de la cámara se calienta un montón, así que es mejor sujetarla por la lente.

**Comment by GioSunrider** [comment]
Si se hace de PETG no habra problemas de temperatura, ya que este aguanta mas las temperaturas que el PLA o ABS.

**Comment by jorgercobo** [comment]
He encontrado uno: https://www.thingiverse.com/thing:2028741
Queda pendiente de probarlo en la próxima reunión :smile:

**Comment by jorgercobo** [comment]
![photo_2018-11-27_21-10-09](https://user-images.githubusercontent.com/9537923/49108628-f1bd7700-f288-11e8-9aff-6c32e5d20772.jpg)

Primera tanda impresa! Pendiente probar las distintas inclinaciones en el coche

**Comment by David-Estevez** [comment]
Me pudo el SAV y diseñé una pieza impresa para sujetar la cámara, que probamos en la pasada reunión:
![image](https://user-images.githubusercontent.com/1451819/49346486-7f3b0580-f693-11e8-824d-74ac3e3c4b16.png)

La pieza fue subida en c0bcc421b822c5c54f86f254a2921cc7f72f59fe

Pese a que me haya podido la impaciencia (:sweat_smile: ) la issue estaba asignada a @jorgercobo así que le dejo a él la decisión de seguir cacharreando con esto y mejorar / modificar las piezas que se han impreso (tanto la que propuso Jorge como la mía) o cerrar la issue y ponernos con la siguiente tarea.

**Comment by David-Estevez** [comment]
Ping @jorgercobo

**Comment by jorgercobo** [comment]
La pieza diseñada por @David-Estevez es mucho mejor que la que propuse, demos por cerrada la issue.
PD: Espero que el SAV ese del que hablas no sea tóxico 
PD 2: Imprusiona alguna más para el resto de prototipos

**Comment by jorgercobo** [comment]
No prefs en cuanto al color, el que menos uses y más te estorbe :smile:
